Update check.yml

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -21,8 +21,8 @@ jobs:
         id: check_vars
         run: |
           if [ "${REPO_NAME}" != "" ] && [ "${REPO_USER}" != "" ]; then
-              echo "Cannot have both variables defined"
-              exit 1
+              echo "Cannot have both variables defined" && exit 1
+              gh run cancel ${{ github.run_id }}
           fi
 
           if [ "${APP_NAME}" != "" ]; then
